//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.28 at 10:33:13 PM PDT 
//


package com.oy.tv.schema.core;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import com.oy.tv.schema.core.EEventType;


/**
 * <p>Java class for EEventType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EEventType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *     &lt;enumeration value="0"/>
 *     &lt;enumeration value="1"/>
 *     &lt;enumeration value="2"/>
 *     &lt;enumeration value="3"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum(Integer.class)
public enum EEventType {

    @XmlEnumValue("1")
    JOINED(1),
    @XmlEnumValue("2")
    JOINED_BUT_DID_NOT_IMMEDIATELY_PLAY(2),
    @XmlEnumValue("0")
    NONE(0),
    @XmlEnumValue("3")
    NO_ACTIVITY_LAST_TWO_WEEKS(3);
    private final int value;

    EEventType(int v) {
        value = v;
    }

    public int value() {
        return value;
    }

    public static EEventType fromValue(int v) {
        for (EEventType c: EEventType.values()) {
            if (c.value == v) {
                return c;
            }
        }
        throw new IllegalArgumentException(String.valueOf(v));
    }

}
