//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.28 at 10:33:13 PM PDT 
//


package com.oy.tv.schema.core;

import javax.xml.bind.annotation.XmlRegistry;
import com.oy.tv.schema.core.AuthTokenBO;
import com.oy.tv.schema.core.BundleBO;
import com.oy.tv.schema.core.CheckpointBO;
import com.oy.tv.schema.core.CorpusBO;
import com.oy.tv.schema.core.CustomerBO;
import com.oy.tv.schema.core.DiffItemBO;
import com.oy.tv.schema.core.EventBO;
import com.oy.tv.schema.core.ObjectCacheBO;
import com.oy.tv.schema.core.ObjectFactory;
import com.oy.tv.schema.core.ProjectionBO;
import com.oy.tv.schema.core.ResponseBO;
import com.oy.tv.schema.core.TagBO;
import com.oy.tv.schema.core.TermBO;
import com.oy.tv.schema.core.TermEditBO;
import com.oy.tv.schema.core.TermsBO;
import com.oy.tv.schema.core.TestBO;
import com.oy.tv.schema.core.TranslationBO;
import com.oy.tv.schema.core.UnitBO;
import com.oy.tv.schema.core.UnitTagBO;
import com.oy.tv.schema.core.UserBO;
import com.oy.tv.schema.core.UserUnitResponseBO;
import com.oy.tv.schema.core.VariationBO;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.oy.tv.schema.core package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oy.tv.schema.core
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CorpusBO }
     * 
     */
    public CorpusBO createCorpusBO() {
        return new CorpusBO();
    }

    /**
     * Create an instance of {@link TranslationBO }
     * 
     */
    public TranslationBO createTranslationBO() {
        return new TranslationBO();
    }

    /**
     * Create an instance of {@link UnitTagBO }
     * 
     */
    public UnitTagBO createUnitTagBO() {
        return new UnitTagBO();
    }

    /**
     * Create an instance of {@link UserBO }
     * 
     */
    public UserBO createUserBO() {
        return new UserBO();
    }

    /**
     * Create an instance of {@link CheckpointBO }
     * 
     */
    public CheckpointBO createCheckpointBO() {
        return new CheckpointBO();
    }

    /**
     * Create an instance of {@link TagBO }
     * 
     */
    public TagBO createTagBO() {
        return new TagBO();
    }

    /**
     * Create an instance of {@link UserUnitResponseBO }
     * 
     */
    public UserUnitResponseBO createUserUnitResponseBO() {
        return new UserUnitResponseBO();
    }

    /**
     * Create an instance of {@link BundleBO }
     * 
     */
    public BundleBO createBundleBO() {
        return new BundleBO();
    }

    /**
     * Create an instance of {@link AuthTokenBO }
     * 
     */
    public AuthTokenBO createAuthTokenBO() {
        return new AuthTokenBO();
    }

    /**
     * Create an instance of {@link CustomerBO }
     * 
     */
    public CustomerBO createCustomerBO() {
        return new CustomerBO();
    }

    /**
     * Create an instance of {@link VariationBO }
     * 
     */
    public VariationBO createVariationBO() {
        return new VariationBO();
    }

    /**
     * Create an instance of {@link ProjectionBO }
     * 
     */
    public ProjectionBO createProjectionBO() {
        return new ProjectionBO();
    }

    /**
     * Create an instance of {@link TestBO }
     * 
     */
    public TestBO createTestBO() {
        return new TestBO();
    }

    /**
     * Create an instance of {@link ObjectCacheBO }
     * 
     */
    public ObjectCacheBO createObjectCacheBO() {
        return new ObjectCacheBO();
    }

    /**
     * Create an instance of {@link TermsBO }
     * 
     */
    public TermsBO createTermsBO() {
        return new TermsBO();
    }

    /**
     * Create an instance of {@link DiffItemBO }
     * 
     */
    public DiffItemBO createDiffItemBO() {
        return new DiffItemBO();
    }

    /**
     * Create an instance of {@link ResponseBO }
     * 
     */
    public ResponseBO createResponseBO() {
        return new ResponseBO();
    }

    /**
     * Create an instance of {@link UnitBO }
     * 
     */
    public UnitBO createUnitBO() {
        return new UnitBO();
    }

    /**
     * Create an instance of {@link EventBO }
     * 
     */
    public EventBO createEventBO() {
        return new EventBO();
    }

    /**
     * Create an instance of {@link TermEditBO }
     * 
     */
    public TermEditBO createTermEditBO() {
        return new TermEditBO();
    }

    /**
     * Create an instance of {@link TermBO }
     * 
     */
    public TermBO createTermBO() {
        return new TermBO();
    }

}
