//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.28 at 10:33:13 PM PDT 
//


package com.oy.tv.schema.core;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import com.oy.tv.schema.core.CorpusBO;
import com.oy.tv.schema.core.ProjectionBO;
import com.oy.tv.schema.core.TermsBO;


/**
 * <p>Java class for ProjectionBO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProjectionBO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="corpus" type="{}CorpusBO"/>
 *         &lt;element name="dimentionFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dimentionTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="relationType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="terms" type="{}TermsBO" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProjectionBO", propOrder = {
    "corpus",
    "dimentionFrom",
    "dimentionTo",
    "relationType",
    "terms"
})
public class ProjectionBO
    implements Serializable
{

    private final static long serialVersionUID = 0L;
    protected CorpusBO corpus;
    protected String dimentionFrom;
    protected String dimentionTo;
    protected String relationType;
    protected List<TermsBO> terms;

    /**
     * Gets the value of the corpus property.
     * 
     * @return
     *     possible object is
     *     {@link CorpusBO }
     *     
     */
    public CorpusBO getCorpus() {
        return corpus;
    }

    /**
     * Sets the value of the corpus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorpusBO }
     *     
     */
    public void setCorpus(CorpusBO value) {
        this.corpus = value;
    }

    /**
     * Gets the value of the dimentionFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDimentionFrom() {
        return dimentionFrom;
    }

    /**
     * Sets the value of the dimentionFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDimentionFrom(String value) {
        this.dimentionFrom = value;
    }

    /**
     * Gets the value of the dimentionTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDimentionTo() {
        return dimentionTo;
    }

    /**
     * Sets the value of the dimentionTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDimentionTo(String value) {
        this.dimentionTo = value;
    }

    /**
     * Gets the value of the relationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationType() {
        return relationType;
    }

    /**
     * Sets the value of the relationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationType(String value) {
        this.relationType = value;
    }

    /**
     * Gets the value of the terms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the terms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTerms().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TermsBO }
     * 
     * 
     */
    public List<TermsBO> getTerms() {
        if (terms == null) {
            terms = new ArrayList<TermsBO>();
        }
        return this.terms;
    }

}
