//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.28 at 10:33:13 PM PDT 
//


package com.oy.tv.schema.core;

import java.io.Serializable;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.oy.tv.schema.core.Adapter1;
import com.oy.tv.schema.core.UserUnitResponseBO;


/**
 * <p>Java class for UserUnitResponseBO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserUnitResponseBO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="unitId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="total" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="correct" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="incorrect" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="lastResponseOn" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserUnitResponseBO", propOrder = {
    "userId",
    "unitId",
    "total",
    "correct",
    "incorrect",
    "lastResponseOn"
})
public class UserUnitResponseBO
    implements Serializable
{

    private final static long serialVersionUID = 0L;
    @XmlElement(type = Integer.class)
    protected int userId;
    @XmlElement(type = Integer.class)
    protected int unitId;
    @XmlElement(type = Integer.class)
    protected int total;
    @XmlElement(type = Integer.class)
    protected int correct;
    @XmlElement(type = Integer.class)
    protected int incorrect;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    protected Calendar lastResponseOn;

    /**
     * Gets the value of the userId property.
     * 
     */
    public int getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     */
    public void setUserId(int value) {
        this.userId = value;
    }

    /**
     * Gets the value of the unitId property.
     * 
     */
    public int getUnitId() {
        return unitId;
    }

    /**
     * Sets the value of the unitId property.
     * 
     */
    public void setUnitId(int value) {
        this.unitId = value;
    }

    /**
     * Gets the value of the total property.
     * 
     */
    public int getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     */
    public void setTotal(int value) {
        this.total = value;
    }

    /**
     * Gets the value of the correct property.
     * 
     */
    public int getCorrect() {
        return correct;
    }

    /**
     * Sets the value of the correct property.
     * 
     */
    public void setCorrect(int value) {
        this.correct = value;
    }

    /**
     * Gets the value of the incorrect property.
     * 
     */
    public int getIncorrect() {
        return incorrect;
    }

    /**
     * Sets the value of the incorrect property.
     * 
     */
    public void setIncorrect(int value) {
        this.incorrect = value;
    }

    /**
     * Gets the value of the lastResponseOn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getLastResponseOn() {
        return lastResponseOn;
    }

    /**
     * Sets the value of the lastResponseOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastResponseOn(Calendar value) {
        this.lastResponseOn = value;
    }

}
