package com.vokamis.ity.mvc;

import com.vokamis.ity.state.StateManager;

public interface IViewManager {
	
	/**
	 * Access to blackboard of persistent state.
	 */
	StateManager getStateManager();
			
	/**
	 * Dispatches action generated by this view. 
	 */
	void dispatch(ICommand commands);
	
	void toast(String message);
	
	void updateStatus(IViewContainer view, String status);

	String getResourceString(int resourceId);
	
	String getAppVersionId();
	
	String getEditionName();
	
}

